final-himedia/APS-Front

- src/app/dashboard/InputDataPanel.js
> feat: 오른쪽 바 초안 수정

- src/app/dashboard/InputDataPanel.js
> feat: 오른쪽 바 초안 최종

- src/app/standard/ListDivider.js
> fetch : 즐겨찾기

- src/app/RootLayout.js
- src/app/scenario/page.js
- src/app/standard/DataGridSection.js
> fetch: Grid 기능 추가(중앙 화면)

- src/app/RootLayout.js
- src/app/layout.js
> fetch: 06/09 병합

- src/app/scenario/[scenarioId]/page.js
- src/app/scenario/bop/bom/page.js
- src/app/scenario/bop/material/page.js
- src/app/scenario/bop/operation/page.js
- src/app/scenario/bop/page.js
- src/app/scenario/bop/plant/page.js
- src/app/scenario/bop/sequence/page.js
- src/app/scenario/config/page.js
- src/app/scenario/layout.js
- src/app/scenario/page.js
- src/app/scenario/resource/mapping/page.js
- src/app/scenario/resource/routing/page.js
- src/app/scenario/resource/tool/page.js
- src/app/scenario/resource/workcenter/page.js
- src/app/scenario/target/page.js
- src/app/standard/InputDataPanel.js
- src/app/standard/ScenarioList.js
> fetch : 폴더구조 정리

- src/app/standard/InputDataPanel.js
> feat : 오른쪽 검색기능

- src/app/RootLayout.js
- src/app/result/layout.js
- src/app/scenario/layout.js
- src/app/standard/InputDataPanel.js
- src/app/standard/RightSidebar.js
> fect : 중간..세이브본

- src/app/scenario/bop/routing/page.js
> merge : 저장본

- src/app/RootLayout.js
- src/app/scenario/layout.js
- src/app/standard/InputDataPanel.js
- src/app/standard/ListDivider.js
- src/global.css
> fetch : 전체적인 스타일 수정했습니다.

- src/app/RootLayout.js
> fetch: 레이아웃 수정06/11

- src/app/scenario/bop/routing/page.js
- src/app/scenario/layout.js
- src/app/scenario/resource/tool-master/page.js
- src/app/standard/Toolbar.js
> feat: 툴바구현중

- src/app/scenario/layout.js
- src/app/scenario/page.js
- src/app/standard/Toolbar.js
> fetch : 툴바수정

- src/app/scenario/layout.js
- src/app/scenario/page.js
- src/app/standard/Toolbar.js
> fetch : 툴바 layout에 적용

- src/app/RootLayout.js
- src/app/login/page.js
- src/app/result/load-stat/page.js
- src/app/result/workcenter-plan/page.js
- src/app/standard/ListDivider.js
- src/app/standard/ResultDataPanel.js
> feat: 로그인페이지, 엔진 실행결과 페이지만듬

- src/app/scenario/bop/bom/page.js
- src/app/scenario/bop/operation-routing/page.js
- src/app/scenario/bop/site/page.js
- src/app/scenario/config/priority/page.js
- src/app/scenario/layout.js
- src/app/scenario/resource/tool-map/page.js
- src/app/scenario/resource/tool-master/page.js
- src/app/scenario/resource/workcenter-map/page.js
- src/app/scenario/resource/workcenter/page.js
- src/app/scenario/target/demand/page.js
- src/app/standard/Toolbar.js
> feat : 엑셀업로드/다운/표 수정중

- src/app/scenario/page.js
> feat : 0616 4시 머지

- src/app/RootLayout.js
- src/app/management/qna/page.js
- src/app/page.js
> feat: 토큰수정

- src/app/scenario/bop/bom/page.js
- src/app/scenario/bop/operation-routing/page.js
- src/app/scenario/bop/operation/page.js
- src/app/scenario/bop/part/page.js
- src/app/scenario/bop/routing/page.js
- src/app/scenario/bop/site/page.js
- src/app/scenario/config/priority/page.js
- src/app/scenario/layout.js
- src/app/scenario/resource/tool-map/page.js
- src/app/scenario/resource/tool-master/page.js
- src/app/scenario/resource/workcenter-map/page.js
- src/app/scenario/resource/workcenter/page.js
- src/app/scenario/target/demand/page.js
> feat : 입력데이터 완성입니다.

- src/app/management/qna/[id]/CommentList.js
- src/app/management/qna/[id]/page.js
- src/app/standard/ListDivider.js
> feat: 댓글기능,즐겨찾기 수정

- src/app/scenario/resource/tool-master/page.js
> feat : 시나리오 약간 수정

- src/app/RootLayout.js
- src/app/components/pathSaver.js
- src/app/login/page.js
- src/app/standard/ListDivider.js
feat: ID저장,새로창열기 기능 마지막페이지저장 기능 완
> feat: ID저장,새로창열기 기능 마지막페이지저장 기능 완

- src/app/RootLayout.js
- src/app/login/page.js
> feat: 페이지저장 완

- src/app/RootLayout.js
- src/app/login/page.js
> feat: 페이지저장 찐막

- src/app/standard/InputDataPanel.js
> feat:즐겨찾기 버튼컬러 수정

- src/app/scenario/bop/operation-routing/page.js
- src/app/standard/ListDivider.js
> feat: 즐겨찾기 버튼컬러 수정

- src/app/scenario/resource/tool-map/page.js
- src/app/scenario/resource/workcenter-map/page.js
- src/app/scenario/target/demand/page.js
- src/app/standard/ScenarioList.js
> feat: 데이터 수정중

- src/app/scenario/target/demand/page.js
> merge : 시나리오 수정0623

- src/app/login/page.js
> feat: 즐겨찾기 오류수정

- src/app/result/lot-merge-history/page.js
- src/app/result/operation-quantity/page.js
- src/app/result/order-list/page.js
- src/app/result/order-log/page.js
- src/app/result/solution-log/page.js
- src/app/result/tool-usage/page.js
- src/app/result/unused-supplies/page.js
- src/app/standard/ListDivider.js
- src/app/standard/ResultDataPanel.js
> feat: 간트수정,결과데이터목록 페이지 생성

- src/app/management/qna/page.js
> merge :QnA 게시판(디자인ing)

- src/app/management/qna/[id]/page.js
- src/app/management/qna/page.js
문의게시판 뒤로가기, 글쓰기 디자인, 댓글등록 구조수정
> feat: 문의게시판 뒤로가기, 글쓰기 디자인, 댓글등록 구조수정

- package-lock.json
- package.json
- src/app/dashboard/FilterToolbar.js
- src/app/dashboard/layout.js
- src/app/dashboard/page.js
- src/app/standard/FilterToolbar.js
- src/app/standard/ListDivider.js
> 대시보드 기본 틀 잡음

- src/app/management/qna/page.js
- src/app/result/load-stat/page.js
- src/app/result/lot-merge-history/page.js
- src/app/standard/Toolbar.js
> feat: 작업장 가동현황 수정

- package-lock.json
- package.json
- src/app/executions/page.js
> merge : 자잘한거 수정

- src/app/result/operation-quantity/page.js
> feat: 공정 별 생산계획

- package-lock.json
- package.json
- src/app/dashboard/FilterToolbar.js
- src/app/executions/ExecutionLogModal.js
- src/app/executions/page.js
- src/app/scenario/bop/operation/page.js
- src/app/standard/ExecutionsToolBar.js
> feat : 실행관리페이지 일부 완성

- src/app/login/page.js
> feat: 비밀번호 찾기

- src/app/dashboard/FilterToolbar.js
- src/app/executions/ExecutionsToolBar.js
- src/app/executions/layout.js
- src/app/executions/page.js
- src/app/result/load-stat/page.js
- src/app/result/workcenter-plan/page.js
- src/app/scenario/bop/operation/page.js
- src/app/standard/ExeScenarioList.js
- src/app/standard/ResultDataPanel.js
- src/app/standard/ResultToolBar.js
> feat : 실행관리&실행결과

- src/app/result/workcenter-plan/page.js
> feat: 오류수정

- src/app/login/RegisterDialog.js
- src/app/login/page.js
- src/app/management/qna/[id]/CommentList.js
- src/app/management/qna/[id]/page.js
- src/app/management/qna/page.js
> feat: 코드설명

- src/app/analysis/production-gantt/page.js
- src/app/layout.js
> feat : 간트 라이센스 수정

- src/app/analysis/production-gantt/page.js
- src/app/dashboard/FilterToolbar.js
- src/app/executions/ExecutionsToolBar.js
- src/app/executions/page.js
- src/app/login/RegisterDialog.js
- src/app/login/page.js
- src/app/management/qna/[id]/CommentList.js
- src/app/management/qna/[id]/page.js
- src/app/management/qna/page.js
- src/app/management/user/change-password/page.js
- src/app/management/user/page.js
- src/app/result/load-stat/page.js
- src/app/result/workcenter-plan/page.js
- src/app/scenario/bop/bom/page.js
- src/app/scenario/bop/operation/page.js
- src/app/scenario/bop/part/page.js
- src/app/scenario/bop/routing/page.js
- src/app/scenario/bop/site/page.js
- src/app/scenario/config/priority/page.js
- src/app/scenario/resource/tool-map/page.js
- src/app/scenario/resource/tool-master/page.js
- src/app/scenario/resource/workcenter-map/page.js
- src/app/scenario/resource/workcenter/page.js
- src/app/scenario/target/demand/page.js
- src/app/standard/ExeScenarioList.js
- src/app/standard/ScenarioList.js
> feat : 경로수정

- src/app/executions/page.js
> feat : 인텔레제관련 경로 수정
